application: ***REMOVED***
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: template/static
- url: /.*
  script: mail_renderer.app

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
