# application: gu-email-renderer
# Please don't check in a target other than QA
# Check the dashboard for the current release number
# version: qa
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: template/static
- url: /admin/.*
  secure: always
  login: admin
  script: admin.app
- url: /.*
  script: mail_renderer.app

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

builtins:
- remote_api: on
